language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
services:
- postgresql
before_script:
- psql -c 'create database dragrace;' -U postgres
script:
- npm run test
true:
  branch: master
deploy:
  provider: heroku
  api_key:
    secure: NzO8BMCnE6sDp0M+ef/+eQLAY+1N1/jRdIWNLmQArZ22Dh4cMzbXCvogF0htxovWfTpBrWgYyNx2idRup0cSY/euVIZGyrhHUYLATZLbJ8AOm1ZhwiR+nbgNGExZcbIQJehDY6A8fjnV9lSeTQWrLQU6rbxY+ang+S8X4HfjFPz02CrawEfkaag3MCeOL2B0zCFG3F3bAc1jNQUys/tiD4ClojPtGQkA45DS31K1EXKAuUD86l8kwQELGRK5/T9zAeAWe5ZSH9qZ+/6CUP4Frhh/QPiwb9GSJg2h9A3ULt+WezT3FQK6xul//t5zBVw0KcVnLgPrhc6DnUo2UlGJF95snmxjQ8zHF4PD+j+BylIza73uNdvfgvKCOaaAnIVOjekcI3gdkD0q1GylHUUBAau3hWTwlNop4dgR9zfoGsChn78ggkYLmhklxKVedMxXTnu5w14GhaFsoFLR9O+xnNa38ZN89wovio5JK8N1TnhBzr4tC4eYE+4nvK+IjUN8FkwE15JMOqiquWQPAdUfPwQ+zKYEWNCAZxnZGvd4S46ZoVZ2/Z0YgRb0L3RWkIT2x5k7fQA5b0Om8/5OFZN0WB9TtkiGlSrkSpsRxUtCcwLFCqOELaWwZm/fCUavkfLsTigd5iL79d5kjimCGx0OpNASHSA3ER1rTM7K7IduA+Q=
  app: dragracedatabase
  on:
    repo: jayhatha/rpdr-tracker
